/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.skht777.markdown.java-application-conventions")
    id("org.beryx.jlink") version "2.24.2"
}

application {
    // Define the main class for the application.
    mainModule.set("com.skht.markdown")
    mainClass.set("com.skht777.markdown.App")
}

jlink {
    launcher {
        name = "markdown"
    }
    mergedModule {
        additive = true
        requires("jdk.crypto.ec")
    }
    options.set(listOf("--compress", "2", "--no-header-files", "--no-man-pages"))
}
