/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("com.skht777.markdown.java-common-conventions")
    id("org.openjfx.javafxplugin")


    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

javafx {
    version = "17"
    modules("javafx.controls", "javafx.fxml", "javafx.web")
}
